### ISSUE TITLE
Update Google Guava

### ISSUE THREAD

**Issue by Spider-Admin** [Bombe/jFCPlib#6]
Hi Bombe,

many thanks for your great jFCPlib. I use it in [Spider ](https://github.com/Spider-Admin/Spider) to create the indexes Clean-Spider and Spider in Hyphanet. Recently I added "GitHub Actions" to all of my projects and now the "Dependabot" shows me 3 warnings because I use the outdated dependency Google Guava:
https://github.com/Spider-Admin/Spider/security/dependabot

This dependency is from your jFCPlib. You are using version 16.0.1, the current version is 33.4.0. Please update this dependency. Thanks.

**Comment by Bombe** [comment]
Hey,

I did you one better, I simply removed it because I wasn’t actually using anything from it. 😄 (Current `next` has d279579.)
